### ISSUE TITLE
Add ES fallback url and upgrade ES Library into Analytics module

### ISSUE THREAD

**Issue by cdgraff** [mediainbox/StreamMachine#10]
- [x] Add support to fallback ES url, allowing pass multiple ES host.
- [x] Upgrade ES library to >= 2.3 that is our current ES version

**Comment by comodinx** [comment]
Added in commit [d9a687aec32be93418fde295ee0f15fc330654db](https://github.com/StreamMachine/StreamMachine/commit/d9a687aec32be93418fde295ee0f15fc330654db)

**Comment by cdgraff** [comment]
We don't need update ApiVersion param from 1.4 to 2.3?

And please can share the example of config you use for development?

**Comment by cdgraff** [comment]
New Setting Example:
```

	"analytics": {
		"finalize_secs": "300",
		"es_uri": [
			"http://node1:9200/index-name",
			"http://node2:9200/index-name",
			"http://node3:9200/index-name"
		]
	}
```
