### ISSUE TITLE
Allow pass GeoIP database file from config

### ISSUE THREAD

**Issue by cdgraff** [mediainbox/StreamMachine#2]
Allow pass GeoIP database file from config file inside slave.json 

https://github.com/mediainbox/StreamMachine/blob/f7184f62ee9171a562870471137ad5c0a7b7f155/src/streammachine/slave/server.coffee#L36-L38

**Comment by comodinx** [comment]
Allowed in commit [76bb0a6320097dcece2c18bf7258ad3b5aa7e237](https://github.com/StreamMachine/StreamMachine/commit/76bb0a6320097dcece2c18bf7258ad3b5aa7e237)
