### ISSUE TITLE
Add support for custom headers

### ISSUE THREAD

**Issue by cdgraff** [mediainbox/StreamMachine#23]
Add support for Custom Headers loaded from Config file

- [x] Allow customize user-agent
https://github.com/mediainbox/StreamMachine/blob/master/src/streammachine/sources/proxy.coffee#L85

- [x] Add support to define a Referer (some server have Referer checks implemented)

Example of new params:
```
		"streams": {
			"bbcworld.mp3": {
				"key": "bbcworld.mp3",
				"root_route": true,
				"format": "mp3",
				"seconds": "900",
				"fallback": "http://bbcwssc.ic.llnwd.net/stream/bbcwssc_mp1_ws-eieuk",
				"fallback_useragent": "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0 like Mac OS X) AppleWebKit/602.1.38 (KHTML, like Gecko) Version/10.0 Mobile/14A5297c Safari/602.1",
				"fallback_referer": "http://www.bbc.co.uk/",
				"source_password": "bbcworld.mp3"
			}
		}
```

**Comment by martindido** [comment]
```
"streams": {
			"bbcworld.mp3": {
				"key": "bbcworld.mp3",
				"root_route": true,
				"format": "mp3",
				"seconds": "900",
				"fallback": "http://bbcwssc.ic.llnwd.net/stream/bbcwssc_mp1_ws-eieuk",
                                "headers": {
                                    "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0 like Mac OS X) AppleWebKit/602.1.38 (KHTML, like Gecko) Version/10.0 Mobile/14A5297c Safari/602.1",
                                    "referer": "http://www.bbc.co.uk/"
                                },
				"source_password": "bbcworld.mp3"
			}
		}
```

**Comment by cdgraff** [comment]
User-agent override is not working:
<pre>
"streams": {
	"c3ushuaia.mp3": {
		"root_route": true,
		"headers": {
			"referer": "https://mediainbox.net/",
			"user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0 like Mac OS X) AppleWebKit/602.1.38 (KHTML, like Gecko) Version/10.0 Mobile/14A5297c Safari/602.1"
		},
		"seconds": "900",
		"format": "mp3",
		"fallback": "http://c3master-sm.mediainbox.net:8000/c3ushuaia.mp3",
		"source_password": "c3ushuaia.mp3",
		"key": "c3ushuaia.mp3"
	}
},
</pre>

![captura de pantalla 2017-05-22 23 15 22](https://cloud.githubusercontent.com/assets/1087447/26335772/9236beac-3f44-11e7-8c27-98aa9ce455bd.png)

**Comment by cdgraff** [comment]
Done!
