### ISSUE TITLE
Upgrade to GeoIP2 DB

### ISSUE THREAD

**Issue by cdgraff** [mediainbox/StreamMachine#3]
Upgrade GeoIP module to v2 

Check the list of NodeJs modules that currently support the V2 here:
http://dev.maxmind.com/geoip/geoip2/downloadable/#MaxMind_APIs

**Comment by comodinx** [comment]
Upgraded in commit [801235e8ac31d0ed488658522d17ae497b78ac92](https://github.com/StreamMachine/StreamMachine/commit/801235e8ac31d0ed488658522d17ae497b78ac92)
