### ISSUE TITLE
Fallback example

### ISSUE THREAD

**Issue by swordsreversed** [mediainbox/StreamMachine#34]
Hi 

I'm looking for a fallback example. This is my stream setup:

```
"lowepost": {
"key": "lowepost",
"format": "aac",
"source_password": "xxx",
"root_route": "true",
"host": "localhost",
"seconds": 3600,
"metaTitle": null,
"source": "lowesource",
"hls": true,
"preroll": "",
"transcoder": "",
"log_interval": 30000,
"meta_interval": 32768,
"max_buffer": 4194304,
"burst": 30,
"fallback": "file:silence.m4a",
"acceptSourceMeta": false,
"log_minutes": true,
"monitored": false,
"metaUrl": "",
"preroll_key": "",
"group": null,
"bandwidth": 0,
"codec": null,
"ffmpeg_args": null,
"stream_key": null,
"impression_delay": 5000
}
```

Also is this more actively maintained than the original repo? Seems pretty dead.

**Comment by cdgraff** [comment]
Hi @swordsreversed yes, we still maintain this project as you can saw in our commits, but we change many things that are not more compatible 100% with original branch.

I never test fallback with FILE; we always use with other Icecast Endpoint, I'll try to test and update here.

But if you run with DEBUG=sm:* possible can get more info about the failure... let me know if have some error that I can read and help.

**Comment by swordsreversed** [comment]
I get 

```
 sm:master:streamer Error: options.uri is a required argument
```
when attempting to start your repo with

```
DEBUG=sm:* ./streammachine-cmd --config ./config/standalone.json
```
