### ISSUE TITLE
added support for IPLock

### ISSUE THREAD

**Issue by cdgraff** [mediainbox/StreamMachine#4]
Add support to Blacklist/Whitelist by IPs, similar to GeoLock but for IP or Range of IP.

This module always be over the GeoLock module, if the user match a rule here don't need to be evaluated by GeoLock module. This way we can allow/deny by IPs, does not matter the GeoLock module say.

Just as reference this module can be useful:
https://www.npmjs.com/package/express-ipfilter

**Comment by comodinx** [comment]
Added in branch [feature/geolock](https://github.com/mediainbox/StreamMachine/tree/feature/geolock)

**Comment by cdgraff** [comment]
To made this works need to add this params into slave.json 

```
	"behind_proxy": true,
  	"geolock": {
  		"enabled": true,
		"config_file": "./config/GeoLite2-Country.mmdb"
 	}
```

And into master.json (this definition is inside each Stream declaration)

```
		        "geolock": {
			        "enabled": true,
			        "mode": "whitelist",
			        "countryCodes": [
		        	        "AR",
		        	        "US",
          				"GB"
        			]
      			}

```
