### ISSUE TITLE
Add Fallback audio for GeoLock

### ISSUE THREAD

**Issue by cdgraff** [mediainbox/StreamMachine#7]
Add the option to define a static audio file as fallback in case that GeoLock rule, denied the play.

Example:

```
	"geolock": {
		"enabled": true,
		"fallback": "http://server.com/audio.mp3"
		"mode": "whitelist",
		"countryCodes": [
			"AR"
		]
	}
```

In case Fallback url is defined, response with 302 code and the location is the fallback url

```
HTTP/1.1 302 Found
Location: http://server.com/audio.mp3
```

**Comment by comodinx** [comment]
Added in commit [93154089418e19e8156795be163916fcbcc23f42](https://github.com/mediainbox/StreamMachine/commit/93154089418e19e8156795be163916fcbcc23f42)
