### ISSUE TITLE
Add fallback Origin

### ISSUE THREAD

**Issue by cdgraff** [mediainbox/StreamMachine#9]
Add the option to declare a Second or N, Masters as Backup, if the Slave loose connection with Master, and after retry N times, go to second Master listed into configuration.

"slave": {
	"master": ["ws://master:8020?password=pass", "ws://master-backup:8020?password=pass"],
	"timeout": 5,
	"retry": 3
}

**Comment by comodinx** [comment]
Added in branch [feature/fallback](https://github.com/mediainbox/StreamMachine/compare/feature/geolock...mediainbox:feature/fallback-origin?expand=1)

**Comment by cdgraff** [comment]
merged
